<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.108" timestamp="2025-05-02T07:48:56.498410-04:00" hostname="Jacks-MBP.localdomain"><testcase classname="" name="tests.integration_tests.integration_test_psnawp_api" time="0.000"><error message="collection failure">/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1387: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1360: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1331: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:935: in _load_unlocked
    ???
.venv/lib/python3.13/site-packages/_pytest/assertion/rewrite.py:185: in exec_module
    exec(co, module.__dict__)
tests/integration_tests/integration_test_psnawp_api/conftest.py:6: in &lt;module&gt;
    from psnawp_api import PSNAWP
src/psnawp_api/__init__.py:3: in &lt;module&gt;
    from psnawp_api.psnawp import PSNAWP
src/psnawp_api/psnawp.py:7: in &lt;module&gt;
    from psnawp_api.core import (
src/psnawp_api/core/__init__.py:14: in &lt;module&gt;
    from psnawp_api.core.authenticator import Authenticator
src/psnawp_api/core/authenticator.py:15: in &lt;module&gt;
    from psnawp_api.utils import API_PATH, BASE_PATH
src/psnawp_api/utils/__init__.py:14: in &lt;module&gt;
    from psnawp_api.utils.misc import extract_region_from_npid, iso_format_to_datetime
src/psnawp_api/utils/misc.py:14: in &lt;module&gt;
    from psnawp_api.core.psnawp_exceptions import PSNAWPInvalidTokenError
E   ImportError: cannot import name 'PSNAWPInvalidTokenError' from 'psnawp_api.core.psnawp_exceptions' (/Users/jack/Source/psnawp/src/psnawp_api/core/psnawp_exceptions.py)</error></testcase></testsuite></testsuites>